GO

CREATE TABLE ThanhToanATM (
	DonHang INT NOT NULL,
	ThoiGianTT DATETIME NOT NULL,
	STK NVARCHAR(15) NOT NULL,
	TenChuKhoan NVARCHAR(50) NOT NULL,
	NganHang NVARCHAR(20) NOT NULL,
	PRIMARY KEY (DonHang, ThoiGianTT)
    
);
GO

CREATE TABLE ThanhToanTienMat (
	DonHang INT NOT NULL,
	ThoiGianTT DATETIME NOT NULL,
	SoTienTraLai DECIMAL(15, 2) NOT NULL,
	PRIMARY KEY (DonHang, ThoiGianTT),
    CONSTRAINT CHK_SoTienTraLai CHECK (SoTienTraLai >= 0)
);
GO

CREATE TABLE NhaCungCap (
	MaNCC INT IDENTITY(1, 1),
	TenNCC VARCHAR(50) NULL,
	DiaChiNCC VARCHAR(100) NULL,
	SDT CHAR(11) NULL,
	Email VARCHAR(50) NULL UNIQUE,
	PRIMARY KEY (MaNCC)
);
GO

CREATE TABLE CungCapLoai (
	MaNCC INT NOT NULL,
	MaLoai INT NOT NULL,
	PRIMARY KEY (MaNCC, MaLoai),
);
GO

CREATE TABLE LoaiSanPham (
	MaLoai INT IDENTITY(1, 1),
	TenLoai NVARCHAR(50) NOT NULL,
	MoTa NVARCHAR(100) NULL,
	PRIMARY KEY (MaLoai)
);
GO

CREATE TABLE SanPham (
	MaSP INT IDENTITY(1, 1),
	TenSP NVARCHAR(50) NOT NULL,
	MoTa NVARCHAR(100) NULL,
	SoLuongTonKho INT NULL,
	MaLoai INT NOT NULL,
	PRIMARY KEY (MaSP),
	CONSTRAINT CHK_SoLuongTonKho CHECK (SoLuongTonKho >= 0)
);
GO

CREATE TABLE LichSuSanPham (
	MaSP INT NOT NULL,
	NgayCapNhatGia DATETIME NOT NULL,
	GiaSP DECIMAL(15, 2) NOT NULL,
	PRIMARY KEY (MaSP, NgayCapNhatGia),
	CONSTRAINT CHK_GiaSP CHECK (GiaSP >= 0)
);
