CREATE DATABASE shop_db
GO
use shop_db
GO
-- drop DATABASE shop_db

CREATE TABLE DONHANG (
    MaDonHang BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NgayLap DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NVLap BIGINT NOT NULL,
    TrangThaiDH CHAR(128) NOT NULL,
)

CREATE TABLE CHITIETDONHANG (
    MaDonHang BIGINT NOT NULL,
    MaSP BIGINT NOT NULL,
    DonGia DECIMAL(15,2) NOT NULL CONSTRAINT positive_dongia CHECK (DonGia > 0.00),
    GiaGiam DECIMAL(15,2) DEFAULT 0.00 CONSTRAINT positive_giagiam CHECK (GiaGiam >= 0.00),
    SoLuong INT DEFAULT 1 CONSTRAINT positive_soluong CHECK (SoLuong > 0),
    
    
    CONSTRAINT PK_CHITIETDONHANG PRIMARY KEY (MaDonHang,MaSP)
)

CREATE TABLE CHITIETDATHANG (
    MaDonDH BIGINT NOT NULL,
    MaSP BIGINT NOT NULL,
    DonGia DECIMAL(15,2) NOT NULL CONSTRAINT positive_dongia_2 CHECK (DonGia > 0.00),
    SoLuong INT DEFAULT 1 CONSTRAINT positive_soluong_2 CHECK (SoLuong > 0),
    
    CONSTRAINT PK_CHITIETDATHANG PRIMARY KEY (MaDonDH,MaSP)
)

CREATE TABLE DONDATHANG (
    MaDonDH BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NgayLap DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NVLap BIGINT NOT NULL,
)

CREATE TABLE DONGIAOHANG (
    MaDonGH BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NgayLap DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MaDonDH BIGINT NOT NULL,
    NVLap BIGINT NOT NULL,
)

CREATE TABLE CHITIETGIAOHANG (
    MaDonGH BIGINT NOT NULL,
    MaSP BIGINT NOT NULL,
    DonGia DECIMAL(15,2) NOT NULL CONSTRAINT positive_dongia_3 CHECK (DonGia > 0.00),
    SoLuong INT DEFAULT 1 CONSTRAINT positive_soluong_3 CHECK (SoLuong > 0),
    
    CONSTRAINT PK_CHITIETGIAOHANG PRIMARY KEY (MaDonGH,MaSP)
)

ALTER TABLE DONHANG ADD CONSTRAINT FK_DONHANG_NHANVIEN FOREIGN KEY (NVLap) REFERENCES NHANVIEN(MaNV)

ALTER TABLE CHITIETDONHANG ADD CONSTRAINT FK_CHITIETDONHANG_DONHANG FOREIGN KEY (MaDonHang) REFERENCES DONHANG(MaDonHang)
ALTER TABLE CHITIETDONHANG ADD CONSTRAINT FK_CHITIETDONHANG_SANPHAM FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)

ALTER TABLE CHITIETDATHANG ADD CONSTRAINT FK_CHITIETDATHANG_DONDATHANG FOREIGN KEY (MaDonDH) REFERENCES DONDATHANG(MaDonDH)
ALTER TABLE CHITIETDATHANG ADD CONSTRAINT FK_CHITIETDATHANG_SANPHAM FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)

ALTER TABLE DONDATHANG ADD CONSTRAINT FK_DONDATHANG_NHANVIEN FOREIGN KEY (NVLap) REFERENCES NHANVIEN(MaNV)

ALTER TABLE DONGIAOHANG ADD CONSTRAINT FK_DONGIAOHANG_NHANVIEN FOREIGN KEY (NVLap) REFERENCES NHANVIEN(MaNV)
ALTER TABLE DONGIAOHANG ADD CONSTRAINT FK_DONGIAOHANG_DONDATHANG FOREIGN KEY (MaDonDH) REFERENCES DONDATHANG(MaDonDH)

ALTER TABLE CHITIETGIAOHANG ADD CONSTRAINT FK_CHITIETGIAOHANG_DONGIAOHANG FOREIGN KEY (MaDonGH) REFERENCES DONGIAOHANG(MaDonGH)
ALTER TABLE CHITIETGIAOHANG ADD CONSTRAINT FK_CHITIETGIAOHANG_SANPHAM FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)


